apiVersion: argovue.io/v1
kind: Service
metadata:
  name: argovue-filebrowser
spec:
  input: []
  helmRelease:
    chart:
      repository: https://jamhed.github.io/charts
      name: filebrowser
      version: 0.1.5
