apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  labels:
    oidc.argovue.io/group: authors
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi
