apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dage-
  labels:
    oidc.argovue.io/group: authors
spec:
  entrypoint: dag
  volumeClaimTemplates:
  - metadata:
      name: work
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Mi
  templates:
  - name: alpine
    retryStrategy:
      limit: 2
    inputs:
      parameters:
      - name: script
    container:
      image: alpine
      command: [sh, -c]
      args: ["{{inputs.parameters.script}}"]
      volumeMounts:
      - name: work
        mountPath: /work
  - name: dag
    dag:
      tasks:
      - name: a
        template: alpine
        arguments:
          parameters: [{name: script, value: "touch /work/a ; sleep 10; echo a"}]
      - name: b
        template: alpine
        arguments:
          parameters: [{name: script, value: "touch /work/b ; sleep 10; echo b; exit 1"}]
      - name: c
        template: alpine
        dependencies: [a, b]
        arguments:
          parameters: [{name: script, value: "touch /work/c ; sleep 10; echo c"}]
