/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	argovueiov1 "argovue/apis/argovue.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppConfigs implements AppConfigInterface
type FakeAppConfigs struct {
	Fake *FakeArgovueV1
	ns   string
}

var appconfigsResource = schema.GroupVersionResource{Group: "argovue.io", Version: "v1", Resource: "appconfigs"}

var appconfigsKind = schema.GroupVersionKind{Group: "argovue.io", Version: "v1", Kind: "AppConfig"}

// Get takes name of the appConfig, and returns the corresponding appConfig object, and an error if there is any.
func (c *FakeAppConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *argovueiov1.AppConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appconfigsResource, c.ns, name), &argovueiov1.AppConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argovueiov1.AppConfig), err
}

// List takes label and field selectors, and returns the list of AppConfigs that match those selectors.
func (c *FakeAppConfigs) List(ctx context.Context, opts v1.ListOptions) (result *argovueiov1.AppConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appconfigsResource, appconfigsKind, c.ns, opts), &argovueiov1.AppConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &argovueiov1.AppConfigList{ListMeta: obj.(*argovueiov1.AppConfigList).ListMeta}
	for _, item := range obj.(*argovueiov1.AppConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appConfigs.
func (c *FakeAppConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appconfigsResource, c.ns, opts))

}

// Create takes the representation of a appConfig and creates it.  Returns the server's representation of the appConfig, and an error, if there is any.
func (c *FakeAppConfigs) Create(ctx context.Context, appConfig *argovueiov1.AppConfig, opts v1.CreateOptions) (result *argovueiov1.AppConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appconfigsResource, c.ns, appConfig), &argovueiov1.AppConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argovueiov1.AppConfig), err
}

// Update takes the representation of a appConfig and updates it. Returns the server's representation of the appConfig, and an error, if there is any.
func (c *FakeAppConfigs) Update(ctx context.Context, appConfig *argovueiov1.AppConfig, opts v1.UpdateOptions) (result *argovueiov1.AppConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appconfigsResource, c.ns, appConfig), &argovueiov1.AppConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argovueiov1.AppConfig), err
}

// Delete takes name of the appConfig and deletes it. Returns an error if one occurs.
func (c *FakeAppConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(appconfigsResource, c.ns, name), &argovueiov1.AppConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &argovueiov1.AppConfigList{})
	return err
}

// Patch applies the patch and returns the patched appConfig.
func (c *FakeAppConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *argovueiov1.AppConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appconfigsResource, c.ns, name, pt, data, subresources...), &argovueiov1.AppConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argovueiov1.AppConfig), err
}
