/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// AppConfigListerExpansion allows custom methods to be added to
// AppConfigLister.
type AppConfigListerExpansion interface{}

// AppConfigNamespaceListerExpansion allows custom methods to be added to
// AppConfigNamespaceLister.
type AppConfigNamespaceListerExpansion interface{}

// DatasetListerExpansion allows custom methods to be added to
// DatasetLister.
type DatasetListerExpansion interface{}

// DatasetNamespaceListerExpansion allows custom methods to be added to
// DatasetNamespaceLister.
type DatasetNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}

// TokenListerExpansion allows custom methods to be added to
// TokenLister.
type TokenListerExpansion interface{}

// TokenNamespaceListerExpansion allows custom methods to be added to
// TokenNamespaceLister.
type TokenNamespaceListerExpansion interface{}
